USE biblioteca_pessoal_1s2026;

SELECT * 
FROM livro;

SELECT 
    T1.ID_USUARIO,
    T2.NOME,
    COUNT(T1.ID_LIVRO) AS QTD_LIVRO,
    SUM(T1.LIDO) AS QTD_LIVRO_LIDO,

    ROUND(
        (SUM(T1.LIDO) / COUNT(T1.ID_LIVRO)) * 100,
        2
    ) AS PCT_LIDO,

    MAX(T1.ANO_PUBLICACAO) AS ANO_MAIS_RECENTE

FROM LIVRO T1

JOIN USUARIO T2 
    ON T1.ID_USUARIO = T2.ID_USUARIO

GROUP BY 
    T1.ID_USUARIO,
    T2.NOME;

/*
CALCULA A IDADE DOS AUTORES
*/

SELECT 
    NOME,
    ANO_NASCIMENTO,
    ANO_MORTE,

    (
        IF(
            ANO_MORTE > 0,
            ANO_MORTE,
            YEAR(CURRENT_DATE())
        ) - ANO_NASCIMENTO
    ) AS IDADE

FROM AUTOR;